/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.hadeuh.tugaspendahuluan12.view;

import id.hadeuh.tugaspendahuluan12.App;
import id.hadeuh.tugaspendahuluan12.model.Pegawai;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author hilmantm
 */
public class AddForm extends javax.swing.JFrame implements InputPage {

    public static final int INSERT_TYPE = 1;
    public static final int EDIT_TYPE = 2;
    
    private Action callback;
    private Pegawai selectedPegawai;
    private int type = -1;
    
    /**
     * Creates new form AddForm
     * @param action
     */
    public AddForm(Action action) {
        this.callback = action;
        this.type = INSERT_TYPE;
        initComponents();
        prepareLayout();
    }
    
    public AddForm(Action action, Pegawai selectedPegawai) {
        this.callback = action;
        this.selectedPegawai = selectedPegawai;
        this.type = EDIT_TYPE;
        initComponents();
        prepareLayout();
    }
    
    private void prepareLayout() {
        fieldStaff.setActionCommand(App.POSISI_STAFF);
        fieldManager.setActionCommand(App.POSISI_MANAGER);
        
        if (this.type == EDIT_TYPE) { 
           fieldNama.setText(selectedPegawai.getNama());
           
           if (selectedPegawai.getPosisi().equals(App.POSISI_STAFF)) {
               fieldStaff.setSelected(true);
           } else {
               fieldManager.setSelected(true);
           }
           
           String[] ttl = selectedPegawai.getTglLahir().toString().split("-");
           fieldTahun.setSelectedItem(ttl[0]);
           fieldBulan.setSelectedItem(ttl[1]);
           fieldTanggal.setSelectedItem(ttl[2]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        fieldStaff = new javax.swing.JRadioButton();
        fieldManager = new javax.swing.JRadioButton();
        fieldTanggal = new javax.swing.JComboBox<>();
        fieldBulan = new javax.swing.JComboBox<>();
        fieldTahun = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pegawai");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Tambah Data Pegawai");

        jLabel2.setText("Nama");

        jLabel3.setText("Posisi");

        jLabel4.setText("Tanggal Lahir");

        fieldNama.setMargin(new java.awt.Insets(2, 8, 2, 6));

        positionGroup.add(fieldStaff);
        fieldStaff.setText("Staff");

        positionGroup.add(fieldManager);
        fieldManager.setText("Manager");

        fieldTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        fieldBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        fieldTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));

        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fieldTanggal, 0, 1, Short.MAX_VALUE)
                                    .addComponent(fieldStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(fieldManager)
                                        .addGap(78, 78, 78))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(fieldNama)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSave)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldStaff)
                    .addComponent(fieldManager))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(cancelBtn))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            validateInput();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null, 
                    e.getMessage(), 
                    "Failed", 
                    JOptionPane.ERROR_MESSAGE);
        }
        
        int tahun = Integer.parseInt(fieldTahun.getSelectedItem().toString());
        int bulan = Integer.parseInt(fieldBulan.getSelectedItem().toString());
        int tanggal = Integer.parseInt(fieldTanggal.getSelectedItem().toString());
        Date ttl = Date.valueOf(String.format("%d-%d-%d", tahun, bulan, tanggal));
        
        Pegawai newPegawai = new Pegawai();
        newPegawai.setNama(fieldNama.getText());
        newPegawai.setPosisi(positionGroup.getSelection().getActionCommand());
        newPegawai.setTglLahir(ttl);
        
        if (this.type == EDIT_TYPE) {
            newPegawai.setId(selectedPegawai.getId());
        }
        
        callback.save(newPegawai, this);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> fieldBulan;
    private javax.swing.JRadioButton fieldManager;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JRadioButton fieldStaff;
    private javax.swing.JComboBox<String> fieldTahun;
    private javax.swing.JComboBox<String> fieldTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.ButtonGroup positionGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void validateInput() throws Exception {
        if (fieldNama.getText().isEmpty()) {
            throw new Exception("Field nama harus diisi");
        }
        
        try {
            positionGroup.getSelection().getActionCommand();
        } catch (Exception e) {
            throw new Exception("Pilih posisi");
        }
    }
}
