/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.hadeuh.tugaspendahuluan12.view;

import id.hadeuh.tugaspendahuluan12.model.Pegawai;
import id.hadeuh.tugaspendahuluan12.repository.Repository;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hilmantm
 */
public class MainForm extends JFrame {

    private Repository pegawaiRepository;
    private ArrayList<Pegawai> employees;
    private Pegawai selectedPegawai = null;
    private int positionSelectedPegawai = -1;
    DefaultListModel model = new DefaultListModel();
    
    /**
     * Creates new form MainForm
     * @param connection
     * @param repository
     */
    public MainForm(Connection connection, Repository repository) {
        this.pegawaiRepository = repository;
        initComponents();
        prepareLayout();
        loadData();
    }
    
    private void prepareLayout() {
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
    }
    
    private void loadData() {
        employees = pegawaiRepository.getAll();
        model.addAll(employees);
        listPegawai.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listPegawai = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        showNama = new javax.swing.JLabel();
        showPosisi = new javax.swing.JLabel();
        showTTL = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jurnal Modul 12");

        listPegawai.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listPegawai);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Daftar Pegawai");

        jLabel2.setText("Nama");

        jLabel3.setText("Posisi");

        jLabel4.setText("Tanggal Lahir");

        showNama.setText("Testing Name");

        showPosisi.setText("Testing Posisi");

        showTTL.setText("Testing TGL");

        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(btnDelete))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit)
                            .addComponent(showTTL)
                            .addComponent(showPosisi)
                            .addComponent(showNama))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnAdd))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(showNama))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(showPosisi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(showTTL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnEdit))
                        .addGap(0, 238, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPegawaiMouseClicked
        selectedPegawai = (Pegawai) model.get(listPegawai.getSelectedIndex());
        positionSelectedPegawai = listPegawai.getSelectedIndex();
        
        showNama.setText(selectedPegawai.getNama());
        showPosisi.setText(selectedPegawai.getPosisi());
        showTTL.setText(selectedPegawai.getTglLahir().toString());
        
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_listPegawaiMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Action<Pegawai, JFrame> callback = new Action<Pegawai, JFrame>() {
            @Override
            public void save(Pegawai result, JFrame frame) {
                int success = pegawaiRepository.insert(result);
                if (success == 1) {
                    model.addElement(result);
                    listPegawai.setModel(model); 
                    JOptionPane.showMessageDialog(null,
                            "Sukses menambahkan pegawai",
                            "Sukses",
                            JOptionPane.INFORMATION_MESSAGE);
                    frame.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Gagal menambahkan pegawai",
                            "Gagal",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        };
        
        AddForm addForm = new AddForm(callback);
        addForm.setLocationRelativeTo(null);
        addForm.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int success = pegawaiRepository.delete(selectedPegawai.getId());
        if (success > 0) {
            model.remove(positionSelectedPegawai);
            listPegawai.setModel(model); 
            JOptionPane.showMessageDialog(null,
                    "Sukses menghapus pegawai",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,
                            "Gagal menghapus pegawai",
                            "Gagal",
                            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        Action<Pegawai, JFrame> callback = new Action<Pegawai, JFrame>() {
            @Override
            public void save(Pegawai result, JFrame frame) {
                int success = pegawaiRepository.edit(result);
                if (success > 0) {
                    model.remove(positionSelectedPegawai);
                    model.addElement(result);
                    listPegawai.setModel(model); 
                    JOptionPane.showMessageDialog(null,
                            "Sukses mengedit pegawai",
                            "Sukses",
                            JOptionPane.INFORMATION_MESSAGE);
                    frame.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Gagal mengedit pegawai",
                            "Gagal",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        };
        
        AddForm addForm = new AddForm(callback, selectedPegawai);
        addForm.setLocationRelativeTo(null);
        addForm.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listPegawai;
    private javax.swing.JLabel showNama;
    private javax.swing.JLabel showPosisi;
    private javax.swing.JLabel showTTL;
    // End of variables declaration//GEN-END:variables
}
